### ISSUE TITLE
New plugins should be based on a differently tagged `fnndsc/ubuntu-python3` image. For instance `fnndsc/ubuntu-python3:18.04` instead of `fnndsc/ubuntu-python3:latest` 

### ISSUE THREAD

**Issue by jbernal0019** [FNNDSC/ubuntu-python3#1]
Otherwise we could face a massive failure of plugins when upgrading the base image and plugin developers unwittingly upgrade their images by committing new plugin code to github.

**Comment by timotta** [comment]
```manifest for fnndsc/ubuntu-python3:18.04 not found```

**Comment by jennydaman** [comment]
https://github.com/FNNDSC/ubuntu-python3/commit/1fa5feecc0e8aa20396b9d4183964092644107c9
